" enter the current millenium
set nocompatible

" enable syntax and plugins (for netrw)
syntax enable
filetype plugin on

" FINDING FILES:

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" Display all matching files when we tab complete
set wildmenu

" NOW WE CAN:
" - Hit tab to :find by partial match
" - Use * to make it fuzzy

" THINGS TO CONSIDER:
" - :b lets you autocomplete any open buffer

" AUTOCOMPLETE:
" HIGHLIGHTS:
" - ^x^n for JUST this file
" - ^x^f for filenames (works with our path trick!)
" - ^x^] for tags only
" - ^n for anything specified by the 'complete' option

" NOW WE CAN:
" - Use ^n and ^p to go back and forth in the suggestion list

" FILE BROWSING:

" Tweaks for browsing
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" NOW WE CAN:
" - :edit a folder to open a file browser
" - <CR>/v/t to open in an h-split/v-split/tab
" - check |netrw-browse-maps| for more mappings

"the above settings are from Youtube video "How to Do 90% of What Plugins Do
"(With Just Vim) , it's a super helpful video , be sure to check it.

" ALSO , you can use "+yy to copy text from vim

" For other setting I use:

"show line numbers
set nu
"auto indent
set ai
" tab = 4 spacebar
set tabstop=4
"how many spacebar a indent will be when you use the shiftwidth function
set shiftwidth=4
"set to transform every tab into space , but don't effect current tab in file.
"use :retab to replace every current tab into space
set expandtab

"let vim more colorful
set t_Co=256

"for editing convenience
:inoremap( ()<Esc>i
:inoremap' ''<Esc>i
:inoremap" ""<Esc>i
:inoremap[ []<Esc>i
:inoremap{ {}<Esc>i

"for cursorline
set cursorline

"for <F5> to run python files
autocmd FileType python map <buffer> <F5> :w<CR>:!clear;python %<CR>
autocmd FileType python imap <buffer> <F5> <Esc>:w<CR>:!clear;python %<CR>

